In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
import ast 
import mysql.connector


db = mysql.connector.connect(host = 'Localhost',
                             username = 'root',
                             password = 'vishal@12345',
                             database = 'netflix')

cur = db.cursor()

In [2]:
Netflix = pd.read_csv('C:\\Users\\visha\\Downloads\\Datasets\\Netflix\\netflix.csv')
Netflix.head()

,title,type,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
0,Five Came Back: The Reference Films,SHOW,1945,TV-MA,48,['documentation'],['US'],1.0,NaN,NaN,NaN
1,Taxi Driver,MOVIE,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0
2,Monty Python and the Holy Grail,MOVIE,1975,PG,91,"['comedy', 'fantasy']",['GB'],NaN,tt0071853,8.2,530877.0
3,Life of Brian,MOVIE,1979,R,94,['comedy'],['GB'],NaN,tt0079470,8.0,392419.0
4,The Exorcist,MOVIE,1973,R,133,['horror'],['US'],NaN,tt0070047,8.1,391942.0

In [3]:
Netflix.isnull().sum()

title                      1
type                       0
release_year               0
age_certification       2610
runtime                    0
genres                     0
production_countries       0
seasons                 3759
imdb_id                  444
imdb_score               523
imdb_votes               539
dtype: int64

Handling Missing Values

In [39]:
Netflix.dropna(subset = ['title'], inplace = True)
Netflix['age_certification'] = Netflix['age_certification'].fillna('Not Available')
Netflix['seasons'] = Netflix['seasons'].fillna(0)
Netflix['imdb_id'] = Netflix['imdb_id'].fillna('Not Available')
Netflix['imdb_score'] = Netflix['imdb_score'].fillna(Netflix['imdb_score'].median())
Netflix['imdb_votes'] = Netflix['imdb_votes'].fillna(Netflix['imdb_votes'].median())

In [5]:
Netflix.isnull().sum()

title                   0
type                    0
release_year            0
age_certification       0
runtime                 0
genres                  0
production_countries    0
seasons                 0
imdb_id                 0
imdb_score              0
imdb_votes              0
dtype: int64

In [6]:
Clean_Netflix = Netflix.to_csv('C:\\Users\\visha\\Downloads\\Datasets\\Netflix\\Clean_Netflix.csv', index = False)

In [7]:
Netflix['genres'] = Netflix['genres'].apply(ast.literal_eval)
Genre_explode = Netflix.explode('genres')

In [8]:
Netflix['production_countries'] = Netflix['production_countries'].apply(ast.literal_eval)
Country_explode = Netflix.explode('production_countries')

In [9]:
Genre_Explode = Genre_explode.to_csv('C:\\Users\\visha\\Downloads\\Datasets\\Netflix\\Genre_Explode.csv', index = False)
Country_Explode = Country_explode.to_csv('C:\\Users\\visha\\Downloads\\Datasets\\Netflix\\Country_Explode.csv', index = False)

In [10]:
from sqlalchemy import create_engine

engine = create_engine(
    'mysql+pymysql://root:vishal%4012345@localhost/netflix'
)

In [30]:
Clean_Netflix = pd.read_csv(r"C:\Users\visha\Downloads\Datasets\Netflix\Clean_Netflix.csv")
Netflix = pd.read_csv(r"C:\Users\visha\Downloads\Datasets\Netflix\Netflix.csv")
Genre_Explode = pd.read_csv(r"C:\Users\visha\Downloads\Datasets\Netflix\Genre_Explode.csv")
Country_Explode = pd.read_csv(r"C:\Users\visha\Downloads\Datasets\Netflix\Country_Explode.csv")

## KPIs & Questions

Total Titles

In [12]:
Total_Titles  =  Clean_Netflix['title'].count()
print(f'Total Titles: {Total_Titles}')

Total Titles: 5805

Total Shows

In [13]:
Total_Shows = (Clean_Netflix['type'] == 'SHOW').sum()
print(f"Total Shows: {Total_Shows}")

Total Shows: 2047

Total Movies

In [14]:
Total_Movies = (Clean_Netflix['type'] == 'MOVIE').sum()
print(f"Total Movies: {Total_Movies}")

Total Movies: 3758

Average IMDb Score

In [15]:
Avg_IMDb_Score = Clean_Netflix['imdb_score'].mean()
print(f"Average IMDb Score: {Avg_IMDb_Score:.2f}")

Average IMDb Score: 6.60

Average Runtime

In [16]:
Avg_Runtime = Clean_Netflix['runtime'].mean()
print(f"Average Runtime: {Avg_Runtime:.2f} minutes")

Average Runtime: 77.66 minutes

Highest Rated Title

In [17]:
Highest_Rated_Title = Clean_Netflix.loc[Clean_Netflix['imdb_score'].idxmax(), 'title']
print(f" The Highest Rated Title: {Highest_Rated_Title} with an IMDb Score of {Clean_Netflix['imdb_score'].max():.2f}")

 The Highest Rated Title: Five Came Back: The Reference Films with an IMDb Score of 6.60

Movies vs Shows

In [18]:
Clean_Netflix['type'].value_counts()

type
MOVIE    3758
SHOW     2047
Name: count, dtype: int64

Percentage Split

In [19]:
Content_Percentage = Clean_Netflix['type'].value_counts(normalize = True)*100
print(f"Content Percentage: {Content_Percentage.round(2)}")

Content Percentage: type
MOVIE    64.74
SHOW     35.26
Name: proportion, dtype: float64

Top 10 Countries

In [20]:
Countries = Country_Explode['production_countries'].value_counts().head(10)
print('Top 10 Production Countries:\n', Countries)

Top 10 Production Countries:
 production_countries
US    2327
IN     629
GB     406
JP     291
FR     248
CA     216
KR     216
ES     212
DE     139
MX     123
Name: count, dtype: int64

Year Trend

In [21]:
Clean_Netflix['release_year'].value_counts().sort_index()

release_year
1945      1
1953      1
1954      2
1956      1
1958      1
       ...
2018    774
2019    848
2020    805
2021    758
2022    217
Name: count, Length: 67, dtype: int64

Most active Year(max Content Release)

In [22]:
Genre_Explode['genres'].value_counts().sort_values(ascending = False).head(10)

genres
drama            2901
comedy           2269
thriller         1178
action           1053
romance           958
documentation     910
crime             891
animation         665
fantasy           631
family            622
Name: count, dtype: int64

Top Genre

In [23]:
Genre_Explode['genres'].value_counts().head(10)

genres
drama            2901
comedy           2269
thriller         1178
action           1053
romance           958
documentation     910
crime             891
animation         665
fantasy           631
family            622
Name: count, dtype: int64

Movies vs Shows by Country

In [24]:
Country_Explode.groupby(['production_countries', 'type']).count().head(10)

                            title  release_year  age_certification  runtime  \
production_countries type
AE                   MOVIE     19            19                 19       19
                     SHOW       2             2                  2        2
AF                   MOVIE      2             2                  2        2
AL                   MOVIE      2             2                  2        2
AO                   MOVIE      1             1                  1        1
AR                   MOVIE     53            53                 53       53
                     SHOW      18            18                 18       18
AT                   MOVIE     10            10                 10       10
                     SHOW       3             3                  3        3
AU                   MOVIE     41            41                 41       41

                            genres  seasons  imdb_id  imdb_score  imdb_votes
production_countries type
AE                   MOVIE      19       19       19          19          19
                     SHOW        2        2        2           2           2
AF                   MOVIE       2        2        2           2           2
AL                   MOVIE       2        2        2           2           2
AO                   MOVIE       1        1        1           1           1
AR                   MOVIE      53       53       53          53          53
                     SHOW       18       18       18          18          18
AT                   MOVIE      10       10       10          10          10
                     SHOW        3        3        3           3           3
AU                   MOVIE      41       41       41          41          41

Average Movie Duration

In [25]:
Clean_Netflix.loc[Clean_Netflix['type'] == 'MOVIE', 'runtime'].mean().round(2)

np.float64(98.81)

Average Show Duration

In [26]:
Clean_Netflix.loc[Clean_Netflix['type'] == 'SHOW', 'runtime'].mean().round(2)

np.float64(38.82)

Longest Movie Runtime

In [27]:
Clean_Netflix.loc[Clean_Netflix['runtime'].idxmax()]

title                   The School of Mischief
type                                     MOVIE
release_year                              1973
age_certification                Not Available
runtime                                    251
genres                              ['comedy']
production_countries                    ['EG']
seasons                                    0.0
imdb_id                          Not Available
imdb_score                                 6.6
imdb_votes                              2279.0
Name: 34, dtype: object

Rating Distribution

In [31]:
Netflix['imdb_score'].value_counts()

imdb_score
6.6    201
6.8    199
6.5    193
6.2    192
7.4    190
      ...
1.9      1
1.5      1
2.4      1
1.6      1
1.8      1
Name: count, Length: 81, dtype: int64

Top Rating by content type

In [ ]:
Netflix.groupby(['type', 'imdb_score'])['title'].count().sort_values(ascending=False)

type   imdb_score
MOVIE  6.2           139
       6.3           137
       6.5           136
       6.6           134
       6.7           123
                    ...
SHOW   1.7             1
       2.6             1
       3.6             1
       3.1             1
       9.5             1
Name: title, Length: 141, dtype: int64

Content Growth Per Year

In [38]:
Clean_Netflix.groupby('release_year')['title'].count().pct_change()*100

release_year
1945           NaN
1953      0.000000
1954    100.000000
1956    -50.000000
1958      0.000000
           ...
2018     33.448276
2019      9.560724
2020     -5.070755
2021     -5.838509
2022    -71.372032
Name: title, Length: 67, dtype: float64